version: '3.9'
services:
  database-sqlserver:
    restart: always
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    image: database-sqlserver
    build:
      context: database-sqlserver
      dockerfile: Dockerfile
    working_dir: /database-sqlserver
    expose:
      - 1443
    ports:
      - 1443:1443
    mem_reservation: 1024M
    mem_limit: 2048M
    cpus: 1.0
  reference-data:
    restart: always
    image: reference-data
    build:
      context: reference-data
      dockerfile: Dockerfile
    working_dir: /reference-data
    expose:
      - 18085
    ports:
      - 18085:18085
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: npm run start
    networks:
      - localnet
  trade-feed:
    restart: always
    image: trade-feed
    build:
      context: trade-feed
      dockerfile: Dockerfile
    working_dir: /trade-feed
    expose:
      - 18086
    ports:
      - 18086:18086
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: npm run start
    networks:
      - localnet
  people-service:
    restart: always
    image: people-service
    build:
      context: people-service
      dockerfile: Dockerfile
    working_dir: /people-service
    expose:
      - 18089
    ports:
      - 18089:18089
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /PeopleService.WebApi dotnet run
    networks:
      - localnet
  account-service:
    restart: always
    image: account-service
    build:
      context: account-service
      dockerfile: Dockerfile
    working_dir: /account-service
    expose:
      - 18088
    ports:
      - 18088:18088
    environment:
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - DATABASE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - DATABASE_URL=jdbc:sqlserver://database-sqlserver:1433;databaseName=traderx;encrypt=true;trustServerCertificate=true;
      - DATABASE_DBUSER=sa
      - DATABASE_DBPASS=YourStrong@Passw0rd
      - PEOPLE_SERVICE_HOST=people-service
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database-sqlserver
      - people-service
  position-service:
    restart: always
    image: position-service
    build:
      context: position-service
      dockerfile: Dockerfile
    working_dir: /position-service
    expose:
      - 18090
    ports:
      - 18090:18090
    environment:
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - DATABASE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - DATABASE_URL=jdbc:sqlserver://database-sqlserver:1433;databaseName=traderx;encrypt=true;trustServerCertificate=true;
      - DATABASE_DBUSER=sa
      - DATABASE_DBPASS=YourStrong@Passw0rd
      - PEOPLE_SERVICE_HOST=people-service
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database-sqlserver
  trade-service:
    restart: always
    image: trade-service
    build:
      context: trade-service
      dockerfile: Dockerfile
    working_dir: /trade-service
    expose:
      - 18092
    ports:
      - 18092:18092
    environment:
      - PEOPLE_SERVICE_HOST=people-service
      - PEOPLE_SERVICE_HOST=people-service
      - ACCOUNT_SERVICE_HOST=account-service
      - REFERENCE_DATA_HOST=reference-data
      - TRADE_FEED_HOST=trade-feed
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database-sqlserver
      - people-service
      - account-service
      - reference-data
      - trade-feed
  trade-processor:
    restart: always
    image: trade-processor
    build:
      context: trade-processor
      dockerfile: Dockerfile
    working_dir: /trade-processor
    expose:
      - 18091
    ports:
      - 18091:18091
    environment:
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - DATABASE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - DATABASE_URL=jdbc:sqlserver://database-sqlserver:1433;databaseName=traderx;encrypt=true;trustServerCertificate=true;
      - DATABASE_DBUSER=sa
      - DATABASE_DBPASS=YourStrong@Passw0rd
      - TRADE_FEED_HOST=trade-feed
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database-sqlserver
      - trade-feed
  web-front-end-angular:
    restart: always
    image: web-front-end-angular
    build:
      context: web-front-end/angular
      dockerfile: Dockerfile
    working_dir: /web-front-end/angular
    expose:
      - 18093
    ports:
      - 18093:18093
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: npm run start
    networks:
      - localnet
    depends_on:
      - database-sqlserver
      - trade-feed
  ingress:
    image: ingress
    build:
      context: ingress
      dockerfile: Dockerfile
      args:
        - NGINX_HOST=${TRADERX_FQDN:-localhost}
    working_dir: /ingress
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - localnet
    depends_on:
      - database-sqlserver
      - trade-feed
      - people-service
      - account-service
      - position-service
      - trade-service
      - trade-processor
      - web-front-end-angular

networks:
  localnet:
    driver: bridge
